services:
    virtual_host_handler:
        class:        FastVPS\CpanelBundle\Handler\VirtualHostHandler
        arguments:    ["%vhost.nginx_conf_dir%", "%vhost.nginx_hosts_dir%", "%vhost.nginx_reload_command%", @file_locator]